### ISSUE TITLE
SleepActions happen at the wrong time

### ISSUE THREAD

**Issue by j5155** [acmerobotics/MeepMeep#6]
When using a SleepAction inside a trajectory using .stopAndAdd, or trying to use a custom action that returns a SleepAction, the delay always occurs at the end of the trajectory instead of at the part where the .stopAndAdd is added.
Using version 0.1.1

To recreate:
Make a trajectory with a SleepAction at the beginning, followed by a movement
Run it
See delay happen at the end instead of the beginning

**Comment by j5155** [comment]
Possibly related: SleepActions appear but are commented out(!) [here](https://github.com/acmerobotics/MeepMeep/blob/5ad6263f5ded7c36e1fa62cea628b9a1a452289a/src/main/kotlin/com/noahbres/meepmeep/roadrunner/entity/ActionEntity.kt#L295)

**Comment by rbrott** [comment]
I was going to say that this has been fixed in 0.1.3, but it turns out that isn't entirely true. I just released 0.1.4 with a fix I'm more confident in. And since I was working on the code, I upgraded RR to 1.0.0-beta8 and released 0.1.5.
